### PR TITLE
Setting new bootsplash image

### PR DESCRIPTION
**Pull request by Flohack74**
As discussed we want to change the splash image to the one with black background on all devices. Taken from https://gitlab.com/rubencarneiro/custom_bootlogos/tree/master/Nexus%205/black

### CODE REVIEW

**Comment by mariogrip** [comment]
Please check these many times to make sure we dont brick any bricks :)

**Comment by Flohack74** [comment]
Just thinking how I can check this. Its hard to test the system image updater without a live update. Any ideas? Could we have a test feed?

**Comment by mariogrip** [comment]
the plan is to move to a better infra a at some point where we will have two system-image service,

one build-system-image and then a production-system-image where all images gets made on the build one, tested by a auto device tests system and then when approved moved to production.

I believe this is more or less what canonical had.

**Review by mariogrip — APPROVED** [review]
LGTM :+1:

**Comment by PJK2011** [comment]
Working fine on my Nexus 5 hammerhead on OTA-10 rc  ver 54 image 2019-W32.

**Comment by Marzal** [comment]
> Working fine on my Nexus 5 hammerhead on OTA-10 rc ver 54 image 2019-W32.

Looking good here too

**Pull request merged**
