### PR TITLE
try to fix timekeep permissions

### PR DESCRIPTION
**Pull request by ghost**
remove the timekeep fro init.hammerhead.rc add time_daemon

### CODE REVIEW

**Comment by peat-psuwit** [comment]
Why do you add time_daemon back? Besides, how can you make time_daemon works with Ubuntu Touch?

**Comment by ghost** [comment]
I added

**Comment by peat-psuwit** [comment]
Just adding time_daemon makes it work right away? Have you tried removing and reinserting battery?

**Comment by ghost** [comment]
Take o look, i removed timekeep from init.xxx.rc that is problem with permissions on timekeep

**Pull request closed without merging**
